version: "3"
services:
  hades:
    build:
      context: ./docker
      args:
        BUILDER_UID: ${UID:-1000}
        BUILDER_GID: ${GID:-100}
    image: hades
    container_name: hades
    network_mode: bridge
    tmpfs:
      - /tmp
      - /run
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    security_opt:
        - seccomp:unconfined
    stdin_open: false
    tty: false
    stop_signal: SIGRTMIN+3
    volumes:
     - /sys/fs/cgroup:/sys/fs/cgroup:ro
     - ../hades-build:/build
     - ./:/build/hades

