version: "3"
services:
  hades:
    build:
      context: ./docker
      args:
        BUILDER_UID: ${UID:-1000}
        BUILDER_GID: ${GID:-1000}
    image: hades
    hostname: hades
    container_name: hades
    network_mode: bridge
    tmpfs:
      - "/tmp:exec"
      - /run
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    security_opt:
        - seccomp:unconfined
    stdin_open: false
    tty: false
    stop_signal: SIGRTMIN+3
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - "home:/build"
      - ./:/build/hades

volumes:
  home:
