FROM network-node-base:latest
MAINTAINER Sebastian Schrader <sebastian.schrader@agdsn.de>

RUN apt-get update -y && apt-get install -y freeradius freeradius-postgresql freeradius-utils

EXPOSE 1812 1813

