#!/bin/bash
set -euo pipefail

readonly EX_OK=0
readonly EX_USAGE=64
readonly EX_UNAVAILABLE=69

msg() {
    echo "$@"
}

print_usage() {
    msg "Usage: $0 COMMAND"
    msg ""
    msg "Available commands"
    msg "  agent          Execute the site node agent (Celery worker)"
    msg "  auth-dhcp      Execute the DHCP server for authenticated users"
    msg "                 (dnsmasq monitored by a SignalProxyDaemon)"
    msg "  auth-dns       Execute the DNS resolver for the authenticated users"
    msg "                 (unbound)"
    msg "  auth-vrrp      Run the VRRP daemon (keepalived, auth)"
    msg "  database       Execute the database (PostgreSQL)"
    msg "  help           Print this help message"
    msg "  init-database  Create database cluster, database, roles, tables,"
    msg "                 views and refresh materialized views."
    msg "                 Add the --clear flag to delete the database."
    msg "  networking     Setup networking (iptables, routing)"
    msg "  radius         Run the RADIUS server (freeRADIUS)"
    msg "  radius-vrrp    Run the VRRP daemon (keepalived, radius)"
    msg "  shell          Start a bash shell for debugging"
    msg "  unauth-dhcp    Run the DHCP server for the unauthenticated users"
    msg "                 (no-op and handled by the unauth-dns dnsmasq)"
    msg "  unauth-dns     Run the DNS resolver (dnsmasq) for the unauth VLAN"
    msg "  unauth-http    Execute the captive portal web server (nginx)"
    msg "  unauth-portal  Run the captive portal WSGI application (using uWSGI)"
    msg "  unauth-vrrp    Run the VRRP daemon (keepalived, unauth)"
}

run_agent() {
    exec python3 -m celery.bin.worker --beat --app=hades.agent --uid="${HADES_AGENT_USER}" --gid="${HADES_AGENT_GROUP}" --workdir="${HADES_AGENT_HOME}"
}

run_auth_dns() {
    python3 -m hades.config.generate unbound.conf.j2 "${HADES_CONFIG_DIR}/unbound.conf"
    exec unbound -c "${HADES_CONFIG_DIR}/unbound.conf"
}

run_auth_dhcp() {
    python3 -m hades.config.generate auth-dnsmasq.conf.j2 "${HADES_CONFIG_DIR}/auth-dnsmasq.conf"
    exec python3 -m hades.dnsmasq.monitor "${HADES_CONFIG_DIR}/auth-dnsmasq.conf"
}

run_auth_vrrp() {
    run_vrrp auth "$@"
}

export_postgres_env() {
    export PATH="/usr/lib/postgresql/${PGVERSION}/bin:${PATH}"
    export PGDATA="/var/lib/postgresql/hades"
}

run_init_database_system() {
    export_postgres_env
    if [[ $(id -u) = 0 ]]; then
        exec python3 -m hades.common.su "${HADES_POSTGRESQL_USER}" "$0" init-database-system "$@"
    fi
    local clear=
    while [[ $# -gt 0 ]]; do
        case $1 in
            --clear) clear=1;;
            *)       msg "Unknown option $1"; exit "${EX_USAGE}";;
        esac
        shift
    done
    clear_pgdata() {
        msg "Clearing ${PGDATA}"
        shopt -s dotglob
        rm -rf "${PGDATA}"/*
        shopt -u dotglob
    }
    [[ -n ${clear} ]] && clear_pgdata
    if [[ -f "${PGDATA}/.cluster-initialized" ]]; then
        msg "Cluster already initialized. Use --clear to delete."
        exit "${EX_UNAVAILABLE}"
    fi
    cleanup_failure() {
        pg_ctl stop -s || true
        clear_pgdata
    }
    trap cleanup_failure EXIT HUP INT QUIT ABRT
    pg_ctl initdb -s -o "--auth-host=reject --auth-local=peer --encoding=UTF-8 --locale=C --nosync"
    python3 -m hades.config.generate postgresql.conf.j2 > "${PGDATA}/postgresql.conf"
    pg_ctl start -w -s
    local user
    for user in "${HADES_RADIUS_USER}" "${HADES_AGENT_USER}" "${HADES_PORTAL_USER}"; do
        createuser "${user}"
    done
    touch "${PGDATA}/.cluster-initialized"
    pg_ctl stop -s
    trap - EXIT HUP INT QUIT ABRT
}

run_init_database_schema() {
    export_postgres_env
    if [[ $(id -u) = 0 ]]; then
        exec python3 -m hades.common.su "${HADES_POSTGRESQL_USER}" "$0" init-database-schema "$@"
    fi
    local clear=
    while [[ $# -gt 0 ]]; do
        case $1 in
            --clear) clear=1;;
            *)       msg "Unknown option $1"; exit "${EX_USAGE}";;
        esac
        shift
    done
    drop_database() {
        msg "Dropping ${HADES_POSTGRESQL_DATABASE}"
        dropdb "${HADES_POSTGRESQL_DATABASE}" || true
    }
    [[ -n ${clear} ]] && drop_database
    if [[ -f "${PGDATA}/.database-initialized" ]]; then
        msg "Database already initialized. Use --clear to delete."
        exit "${EX_UNAVAILABLE}"
    fi
    cleanup_failure() {
        drop_database
        pg_ctl stop -s || true
    }
    trap cleanup_failure EXIT HUP INT QUIT ABRT
    pg_ctl start -w -s
    createdb "${HADES_POSTGRESQL_DATABASE}"
    python3 -m hades.config.generate schema.sql.j2 | psql --quiet --set=ON_ERROR_STOP=1 --no-psqlrc --single-transaction --file=- "${HADES_POSTGRESQL_DATABASE}"
    touch "${PGDATA}/.database-initialized"
    pg_ctl stop -s
    trap - EXIT HUP INT QUIT ABRT
}

run_init_database() {
    export_postgres_env
    if [[ ! -f "${PGDATA}/.cluster-initialized" ]]; then
        "$0" init-database-system "$@"
    fi
    if [[ ! -f "${PGDATA}/.database-initialized" ]]; then
        "$0" init-database-schema "$@"
    fi
}

run_database() {
    export_postgres_env
    "$0" init-database "$@"
    exec python3 -m hades.common.su "${HADES_POSTGRESQL_USER}" postgres
}

run_networking() {
    if [[ "${HADES_CREATE_DUMMY_INTERFACES-False}" = True ]]; then
        local interface
        for interface in "${HADES_RADIUS_INTERFACE}" "${HADES_VRRP_INTERFACE}" "${HADES_AUTH_INTERFACE}" "${HADES_UNAUTH_INTERFACE}"; do
            if [[ -d "/sys/class/net/${interface}" ]]; then
                continue
            fi
            ip link add name "${interface}" type dummy
            ip link set up dev "${interface}"
        done
    fi

    sysctl net.ipv4.ip_nonlocal_bind=1
    local netns
    for netns in auth unauth; do
        ip netns add "${netns}"
        ip netns exec "${netns}" ip link set dev lo up
        ip netns exec "${netns}" sysctl net.ipv4.ip_nonlocal_bind=1
    done

    # After moving interfaces they are DOWN.
    ip link set dev "${HADES_AUTH_INTERFACE}" netns auth
    ip netns exec auth ip link set dev "${HADES_AUTH_INTERFACE}" up
    ip link set dev "${HADES_UNAUTH_INTERFACE}" netns unauth
    ip netns exec unauth ip link set dev "${HADES_UNAUTH_INTERFACE}" up

    # Create virtual ethernet adapters and put the other end into the correct
    # namespace.
    ip link add name eth-auth type veth peer netns auth name eth0
    ip link add name eth-unauth type veth peer netns unauth name eth0

    # Create bridge
    if [[ ! -d "/sys/class/net/${HADES_VRRP_BRIDGE}" ]]; then
        # Not all settings available with iproute2.
        brctl addbr "${HADES_VRRP_BRIDGE}"
        brctl setfd "${HADES_VRRP_BRIDGE}" 0
        brctl stp "${HADES_VRRP_BRIDGE}" off
    fi

    # Create bridge and virtual adapters for the separate VRRP network.
    ip link add name eth-auth-vrrp type veth peer netns auth name vrrp
    ip link add name eth-unauth-vrrp type veth peer netns unauth name vrrp
    ip link set dev eth-auth-vrrp master "${HADES_VRRP_BRIDGE}" up
    ip link set dev eth-unauth-vrrp master "${HADES_VRRP_BRIDGE}" up
    ip link set dev "${HADES_VRRP_INTERFACE}" master "${HADES_VRRP_BRIDGE}" up
    ip link set dev "${HADES_VRRP_BRIDGE}" up
    ip netns exec auth ip link set vrrp up
    ip netns exec unauth ip link set vrrp up

    # Setup the interfaces virtual interfaces connecting the different
    # namespaces.
    ip link set dev eth-auth up
    ip netns exec auth ip link set dev eth0 up
    ip link set dev eth-unauth up
    ip netns exec unauth ip link set dev eth0 up

    python3 -m hades.config.generate iptables-main.j2 | iptables-restore
    for netns in auth unauth; do
        python3 -m hades.config.generate "iptables-${netns}.j2" | ip netns exec "${netns}" iptables-restore
    done
    exit ${EX_OK}
}

run_networking_shutdown() {
    # No early exit if some things fail.
    set +e

    sysctl net.ipv4.ip_nonlocal_bind=0
    local netns
    for netns in auth unauth; do
        ip netns del "${netns}"
        ip link del dev eth-"${netns}"
    done

    local i
    local -a tables=(filter filter filter  nat        nat         nat)
    local -a chains=(INPUT  OUTPUT FORWARD PREROUTING POSTROUTING OUTPUT)
    for (( i = 0; i < "${#tables[@]}"; i++ )); do
        iptables --table "${tables[$i]}" --flush "${chains[$i]}"
    done
}

run_radius() {
    python3 -m hades.config.generate freeradius "${HADES_CONFIG_DIR}/freeradius"
    local -r timeout=30
    local i
    # Wait until database is available
    for i in $(seq "${timeout}"); do
        python3 -m hades.common.check_db 2 &>/dev/null && break
        sleep 1
    done
    python3 -m hades.common.check_db
    exec freeradius -f -m -d "${HADES_CONFIG_DIR}/freeradius"
}

run_radius_vrrp() {
    run_vrrp radius "$@"
}

run_shell() {
    exec bash
}

run_unauth_dhcp() {
    msg "DHCP for the unauth VLAN is currently performed by the dnsmasq "
    msg "instance that provides unauth DNS."
    exit ${EX_OK}
}

run_unauth_dns() {
    python3 -m hades.config.generate unauth-dnsmasq.conf.j2 "${HADES_CONFIG_DIR}/unauth-dnsmasq.conf"
    exec dnsmasq -k -C "${HADES_CONFIG_DIR}/unauth-dnsmasq.conf"
}

run_unauth_http() {
    python3 -m hades.config.generate nginx "${HADES_CONFIG_DIR}/nginx"
    # Next two lines are not working, see https://bugzilla.redhat.com/show_bug.cgi?id=1212756
    #ln -nsf /dev/stdout /var/log/nginx/access.log
    #ln -nsf /dev/stderr /var/log/nginx/error.log
    exec nginx -c "${HADES_CONFIG_DIR}/nginx/nginx.conf"
}

run_unauth_portal() {
    python3 -m hades.config.generate uwsgi.ini.j2 "${HADES_CONFIG_DIR}/uwsgi.ini"
    exec uwsgi --ini="${HADES_CONFIG_DIR}/uwsgi.ini"
}

run_unauth_vrrp() {
    run_vrrp unauth "$@"
}

run_vrrp() {
    case "$1" in
        auth|radius|unauth) ;;
        *) msg "Unknown option $1"; exit "${EX_USAGE}";;
    esac
    python3 -m hades.config.generate "keepalived-$1.conf.j2" "${HADES_CONFIG_DIR}/keepalived-$1.conf"
    exec keepalived --log-console --dont-fork --vrrp --use-file="${HADES_CONFIG_DIR}/keepalived-$1.conf" --pid="/run/hades/vrrp/keepalived-$1.pid" --vrrp_pid="/run/hades/vrrp/vrrp-$1.pid"
}

main() {
    source <(python3 -m hades.config.export)
    local command
    if [[ $# -lt 1 ]]; then
        command=help
    else
        command=$1
        shift
    fi
    case "$command" in
        agent|auth-dhcp|auth-dns|auth-vrrp|database|init-database|init-database-system|init-database-schema|networking|networking-shutdown|radius|radius-vrrp|shell|unauth-dhcp|unauth-dns|unauth-http|unauth-portal|unauth-vrrp)
            "run_${command//-/_}" "$@"
            ;;
        help|-h|--help)
            print_usage
            exit ${EX_OK}
            ;;
        *)
            msg "Unknown command: $command"
            print_usage
            exit ${EX_USAGE}
            ;;
    esac
}

main "$@"
