#!/usr/bin/dh-exec
conf/*.service usr/lib/systemd/system/
conf/*.target usr/lib/systemd/system/
conf/*.timer usr/lib/systemd/system/
conf/config.py etc/hades
conf/hades.busconfig => etc/dbus-1/system.d/de.agdsn.hades.conf
conf/hades.default => etc/default/hades
conf/hades.tmpfile => etc/tmpfiles.d/hades.conf
templates/* usr/share/hades/templates
locales/de/LC_MESSAGES/hades.mo usr/share/locales/de/LC_MESSAGES
scripts/*.sh usr/lib/hades
