BABEL_DEFAULT_LOCALE = 'de_DE'
BABEL_DEFAULT_TIMEZONE = 'Europe/Berlin'
SECRET_KEY = 'AGvSyMEndGmmrLjGvzP6'
SQLALCHEMY_DATABASE_URI = 'postgresql:///radius'
DEBUG = True
HADES_REAUTHENTICATION_INTERVAL = 300
